// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VerdanskGameBot.GameServer.Db;

#nullable disable

namespace VerdanskGameBot.Migrations.SqlServer
{
    [DbContext(typeof(GameServerSqlServerDb))]
    partial class GameServerSqlServerDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VerdanskGameBot.GameServer.GameServerModel", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("ServerName")
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)");

                    b.Property<decimal>("AddedBy")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTimeOffset>("AddedSince")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("AddedSinceUTC");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("GameLink")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GamePort")
                        .HasColumnType("int");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTimeOffset>("LastOnline")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LastOnlineUTC");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LastUpdateUTC");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<TimeSpan>("UpdateInterval")
                        .HasColumnType("time");

                    b.HasKey("Id", "ServerName");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id", "ServerName"));

                    b.ToTable("GameServers");
                });
#pragma warning restore 612, 618
        }
    }
}
