// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VerdanskGameBot.GameServer;

#nullable disable

namespace VerdanskGameBot.Migrations
{
    [DbContext(typeof(GameServerDb))]
    partial class GameServerDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VerdanskGameBot.GameServer.GameServerModel", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    b.Property<ulong>("AddedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("added_by");

                    b.Property<string>("AddedSince")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("added_since");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("chan_id");

                    b.Property<string>("GameLink")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("game_link");

                    b.Property<ushort>("GamePort")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("game_port");

                    b.Property<string>("GameType")
                        .HasMaxLength(22)
                        .HasColumnType("varchar(22)")
                        .HasColumnName("type");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("varchar(45)")
                        .HasColumnName("game_ip");

                    b.Property<string>("LastOnline")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_online_time");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_update");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("msg_id");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("varchar(22)")
                        .HasColumnName("name");

                    b.Property<string>("UpdateInterval")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("update_interval");

                    b.HasKey("Id");

                    b.ToTable("gameservers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
