// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VerdanskGameBot.GameServer.Db;

#nullable disable

namespace VerdanskGameBot.Migrations.MySql
{
    [DbContext(typeof(GameServerMySqlDb))]
    partial class GameServerMySqlDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VerdanskGameBot.GameServer.GameServerModel", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("ServerName")
                        .HasMaxLength(22)
                        .HasColumnType("varchar(22)");

                    b.Property<ulong>("AddedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTimeOffset>("AddedSince")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("AddedSinceUTC");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("GameLink")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<ushort>("GamePort")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("varchar(22)");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<DateTimeOffset>("LastOnline")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LastOnlineUTC");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LastUpdateUTC");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<TimeSpan>("UpdateInterval")
                        .HasColumnType("time(6)");

                    b.HasKey("Id", "ServerName")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("GameServers");
                });
#pragma warning restore 612, 618
        }
    }
}
