// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VerdanskGameBot.GameServer.Db;

#nullable disable

namespace VerdanskGameBot.Migrations.SqlServer
{
    [DbContext(typeof(GameServerSqlServerDb))]
    partial class GameServerSqlServerDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VerdanskGameBot.GameServer.GameServerModel", b =>
                {
                    b.Property<string>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("AddedSince")
                        .HasColumnType("datetime2")
                        .HasColumnName("AddedSinceUTC");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("GameLink")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GamePort")
                        .HasColumnType("int");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("LastModifiedSince")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModifiedSinceUTC");

                    b.Property<DateTime>("LastOnline")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastOnlineUTC");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastUpdateUTC");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)");

                    b.Property<TimeSpan>("UpdateInterval")
                        .HasColumnType("time");

                    b.HasKey("ServerId");

                    b.HasIndex(new[] { "ServerName" }, "IX_ServerName")
                        .IsUnique();

                    b.ToTable("GameServers");
                });
#pragma warning restore 612, 618
        }
    }
}
