// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VerdanskGameBot.GameServer.Db;

#nullable disable

namespace VerdanskGameBot.GameServer.Db.MigrationHandler.sqlite
{
    [DbContext(typeof(GameServerDb))]
    [Migration("20250910112920_Commit_35011ce")]
    partial class Commit_35011ce
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("VerdanskGameBot.GameServer.Db.Models.GameServerHistory", b =>
                {
                    b.Property<long>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("AddedBy")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AddedSince")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AddedSinceUTCTicks");

                    b.Property<long>("ChangedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ChangedAtUTCTicks");

                    b.Property<ulong>("ChangedBy")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameLink")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameLinkRemarks")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("GamePort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("TEXT");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("LastModifiedBy")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastModifiedSince")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastModifiedSinceUTCTicks");

                    b.Property<long?>("LastOnline")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastOnlineUTCTicks");

                    b.Property<long?>("LastUpdate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastUpdateUTCTicks");

                    b.Property<byte?>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NextUpdateAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NextUpdateAtUTCTicks");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<byte?>("Players")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remarks")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<long>("ServerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdateInterval")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdateIntervalHMSTicks");

                    b.HasKey("HistoryId");

                    b.HasIndex(new[] { "ChangedAt" }, $"IX_history_ChangedAt_{guildHex}");

                    b.HasIndex(new[] { "ServerId" }, $"IX_history_ServerId_{guildHex}");

                    b.HasIndex(new[] { "ServerId", "ChangedAt" }, $"IX_history_Server_Changed_{guildHex}");

                    b.ToTable($"gameserver_{guildHex}_history", (string)null);
                });

            modelBuilder.Entity("VerdanskGameBot.GameServer.Db.Models.GameServerModel", b =>
                {
                    b.Property<long>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("AddedBy")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AddedSince")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AddedSinceUTCTicks");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameLink")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameLinkRemarks")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("GamePort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("TEXT");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("LastModifiedBy")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastModifiedSince")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastModifiedSinceUTCTicks");

                    b.Property<long?>("LastOnline")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastOnlineUTCTicks");

                    b.Property<long?>("LastUpdate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastUpdateUTCTicks");

                    b.Property<byte?>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NextUpdateAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NextUpdateAtUTCTicks");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<byte?>("Players")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdateInterval")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdateIntervalHMSTicks");

                    b.HasKey("ServerId");

                    b.HasIndex(new[] { "ServerName" }, $"IX_ServerName_{guildHex}")
                        .IsUnique();

                    b.ToTable($"gameservers_{guildHex}", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
