<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
	  <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <Version>1.0.0-rc1</Version>
    <Authors>ha-ves</Authors>
    <Company>Tekat</Company>
    <Product>Verdansk Game Bot | Game Server Watcher</Product>
	<Title>$(Product)</Title>
	  <Copyright>Copyright (c) $([System.DateTime]::UtcNow.ToString("yyyy")) Tekat, ha-ves. All rights reserved.</Copyright>
  </PropertyGroup>

	<PropertyGroup>
		<DebugType>embedded</DebugType>
		<FileAlignment>512</FileAlignment>
		<BuildOS>Windows</BuildOS>
		<DevMode>true</DevMode>
	
		<DefineConstants Condition="$(BuildOS) == 'Windows'">$(DefineConstants);BUILD_WINDOWS;</DefineConstants>
		<DefineConstants Condition="$(BuildOS) == 'Linux'">$(DefineConstants);BUILD_LINUX;</DefineConstants>
		<DefineConstants Condition="$(BuildOS) == 'OSX'">$(DefineConstants);BUILD_OSX;</DefineConstants>

		<DefineConstants Condition="'$(DevMode)' != ''">$(DefineConstants);DEV;</DefineConstants>
	</PropertyGroup>

	<!--shipping with nodejs & gamedig-->
	<PropertyGroup>
		<PackageWithNodeGamedig>false</PackageWithNodeGamedig>
		<NodeJSExecPath>nodejs/</NodeJSExecPath>
	</PropertyGroup>

	<!--when shipping with nodejs & gamedig-->
	<ItemGroup Condition="'$(PackageWithNodeGamedig)' == 'true'">
		<AssemblyAttribute Include="$(AssemblyName).Ext.AssemblyNodeJSAttribute">
			<!--Path--><_Parameter1>$(NodeJSExecPath)</_Parameter1>
		</AssemblyAttribute>

		<Content Include="node_modules\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="$(NodeJSExecPath)\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
        <Content Include="package*.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	
	<!--when default-->
	<ItemGroup Condition="'$(PackageWithNodeGamedig)' != 'true'">
		<Compile Remove="node_modules\**" />
		<EmbeddedResource Remove="node_modules\**" />
		<None Remove="node_modules\**" />
		
		<Compile Remove="$(NodeJSExecPath)\**" />
		<EmbeddedResource Remove="$(NodeJSExecPath)\**" />
		<None Remove="$(NodeJSExecPath)\**" />
		
		<None Remove="package*.json" />
	</ItemGroup>
	
	<!--Embedded Resources-->
	<ItemGroup>
		<None Remove="EmbedRes\**\*" />
		
		<EmbeddedResource Include="EmbedRes\**\*">
			<LogicalName>%(Filename)%(Extension)</LogicalName>
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <!--Bot-->
    <PackageReference Include="Discord.Net" Version="3.18.0" />
	  
	  <!--Querying-->
    <PackageReference Include="HtmlAgilityPack" Version="1.12.2" />
    <PackageReference Include="Jering.Javascript.NodeJS" Version="7.0.0" />
    <PackageReference Include="Markdig.Signed" Version="0.41.3" />
	  
	<!--Logging-->
	<PackageReference Include="NLog" Version="6.0.3" />
	<PackageReference Include="NLog.Extensions.Logging" Version="6.0.3" />

	<!--Misc-->
	<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.8" />
	<PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="9.0.8" />
	<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.0.8" />

	</ItemGroup>

	<!--Database Lib Projects-->
	<ItemGroup>
	  <ProjectReference Include="..\Databases\GameServerDb\GameServer.Db.csproj" />
	</ItemGroup>

</Project>
